/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HelpSeeker;

/**
 *
 * @author Sakshi Sasalate
 */
public class WriteTestimonialForVol extends javax.swing.JPanel {

    /**
     * Creates new form WriteTestimonialForVol
     */
    public WriteTestimonialForVol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manageEnt = new javax.swing.JLabel();
        manageEnt1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        helpRequestsJTable = new javax.swing.JTable();
        writeTestimonialBtn = new javax.swing.JButton();
        writeTestPanel = new javax.swing.JLayeredPane();
        submitTestimnialBtn = new javax.swing.JButton();
        LastName = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        viewYourProfile = new javax.swing.JLabel();
        helpNameTxtField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        firstName = new javax.swing.JLabel();
        firstName1 = new javax.swing.JLabel();
        serviceTypeTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        testiTxtAreaField = new javax.swing.JTextArea();
        LastName1 = new javax.swing.JLabel();
        viewYourProfile1 = new javax.swing.JLabel();
        LastName2 = new javax.swing.JLabel();
        ViewVolunteerProfileBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        manageEnt.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt.setText("Write Testimonial");

        manageEnt1.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt1.setText("Heart Help ");

        helpRequestsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Help Recieved", "Requested Date", "Volunteer Name", "Resolved Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(helpRequestsJTable);

        writeTestimonialBtn.setText("Write Testimonial");
        writeTestimonialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeTestimonialBtnActionPerformed(evt);
            }
        });

        writeTestPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        submitTestimnialBtn.setText("Submit");
        submitTestimnialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTestimnialBtnActionPerformed(evt);
            }
        });

        LastName.setText("Last Name:");

        cancelBtn.setText("Cancel");

        jLabel1.setText("Please enter characters below 500");

        lastNameField.setEditable(false);
        lastNameField.setEnabled(false);

        viewYourProfile.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        viewYourProfile.setText("Volunteer Details:");

        helpNameTxtField.setEditable(false);
        helpNameTxtField.setEnabled(false);
        helpNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpNameTxtFieldActionPerformed(evt);
            }
        });

        firstNameField.setEditable(false);
        firstNameField.setEnabled(false);

        firstName.setText("First Name:");

        firstName1.setText("Help Recieved");

        serviceTypeTxtField.setEditable(false);
        serviceTypeTxtField.setEnabled(false);

        testiTxtAreaField.setColumns(20);
        testiTxtAreaField.setRows(5);
        jScrollPane1.setViewportView(testiTxtAreaField);

        LastName1.setText("Help Type:");

        viewYourProfile1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        viewYourProfile1.setText("Help Recieved:");

        LastName2.setText("Testimonial");

        writeTestPanel.setLayer(submitTestimnialBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(LastName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(cancelBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(lastNameField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(viewYourProfile, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(helpNameTxtField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(firstNameField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(firstName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(firstName1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(serviceTypeTxtField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(LastName1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(viewYourProfile1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        writeTestPanel.setLayer(LastName2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout writeTestPanelLayout = new org.jdesktop.layout.GroupLayout(writeTestPanel);
        writeTestPanel.setLayout(writeTestPanelLayout);
        writeTestPanelLayout.setHorizontalGroup(
            writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(writeTestPanelLayout.createSequentialGroup()
                .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(writeTestPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(viewYourProfile)
                            .add(writeTestPanelLayout.createSequentialGroup()
                                .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(firstName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(LastName))
                                .add(18, 18, 18)
                                .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(lastNameField)
                                    .add(firstNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(viewYourProfile1)
                            .add(writeTestPanelLayout.createSequentialGroup()
                                .add(112, 112, 112)
                                .add(submitTestimnialBtn)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cancelBtn))
                            .add(writeTestPanelLayout.createSequentialGroup()
                                .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(LastName1)
                                    .add(firstName1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(LastName2))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 362, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(writeTestPanelLayout.createSequentialGroup()
                                        .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, serviceTypeTxtField)
                                            .add(helpNameTxtField))
                                        .add(183, 183, 183))))))
                    .add(writeTestPanelLayout.createSequentialGroup()
                        .add(136, 136, 136)
                        .add(jLabel1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        writeTestPanelLayout.setVerticalGroup(
            writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(writeTestPanelLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(viewYourProfile)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(firstName)
                    .add(firstNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(LastName)
                    .add(lastNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26)
                .add(viewYourProfile1)
                .add(18, 18, 18)
                .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(firstName1)
                    .add(helpNameTxtField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16)
                .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(LastName1)
                    .add(serviceTypeTxtField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(writeTestPanelLayout.createSequentialGroup()
                        .add(52, 52, 52)
                        .add(LastName2))
                    .add(writeTestPanelLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(writeTestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(submitTestimnialBtn)
                    .add(cancelBtn))
                .addContainerGap())
        );

        ViewVolunteerProfileBtn.setText("View Volunteer Profile");
        ViewVolunteerProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewVolunteerProfileBtnActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(manageEnt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 233, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 496, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(backJButton))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(34, 34, 34)
                        .add(ViewVolunteerProfileBtn)
                        .add(53, 53, 53)
                        .add(writeTestimonialBtn)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 76, Short.MAX_VALUE)
                .add(writeTestPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(35, 35, 35))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .add(377, 377, 377)
                    .add(manageEnt1)
                    .addContainerGap(609, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(92, 92, 92)
                        .add(manageEnt)
                        .add(18, 18, 18)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(31, 31, 31)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(ViewVolunteerProfileBtn)
                            .add(writeTestimonialBtn))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(backJButton))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(writeTestPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .add(33, 33, 33)
                    .add(manageEnt1)
                    .addContainerGap(454, Short.MAX_VALUE)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1124, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 519, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void writeTestimonialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeTestimonialBtnActionPerformed
        int selectedRow = helpRequestsJTable.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(this, "Please select a row", "warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }

        NeedHelpWorkRequest nhwr = (NeedHelpWorkRequest)helpRequestsJTable.getValueAt(selectedRow, 1);
        if(nhwr.getReceiver()==null)
        {
            JOptionPane.showMessageDialog(this, "Request has not been processed yet", "warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        volunteer = (Volunteer)nhwr.getReceiver().getPerson();

        firstNameField.setText(volunteer.getFirstName());
        lastNameField.setText(volunteer.getLastName());
        helpNameTxtField.setText(nhwr.getNeedHelp().getHelp());
        serviceTypeTxtField.setText(nhwr.getNeedHelp().getServiceType());
        writeTestPanel.setVisible(true);

    }//GEN-LAST:event_writeTestimonialBtnActionPerformed

    private void submitTestimnialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTestimnialBtnActionPerformed

        if(testiTxtAreaField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please write few words about volunteer service!", "warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        if(testiTxtAreaField.getText().length()>500)
        {
            JOptionPane.showMessageDialog(this, "Please enter text less than 500 characters", "warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        try
        {

            Testimonial testimonial = volunteer.addTestimonial();
            testimonial.setTestimonialTxt(testiTxtAreaField.getText().replaceAll("\n", " "));

            DateFormat df = new SimpleDateFormat("EEE, MMM d, YYYY hh:mm aaa");
            Calendar cal = Calendar.getInstance();
            String timestamp = df.format(cal.getTime());
            testimonial.setWriterName(userAccount.getPerson().getName());
            testimonial.setDate(timestamp);

            JOptionPane.showMessageDialog(this, "Testimonial has been created Succesfully, Thank You", "success", JOptionPane.PLAIN_MESSAGE);
            testiTxtAreaField.setText("");
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Please enter valid data", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }//GEN-LAST:event_submitTestimnialBtnActionPerformed

    private void helpNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpNameTxtFieldActionPerformed

    private void ViewVolunteerProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewVolunteerProfileBtnActionPerformed
        int selectedRow = helpRequestsJTable.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(this, "Please select a row", "warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }

        NeedHelpWorkRequest nhwr = (NeedHelpWorkRequest)helpRequestsJTable.getValueAt(selectedRow, 1);
        if(nhwr.getReceiver() == null)
        {
            JOptionPane.showMessageDialog(this, "Request has not been processed yet", "warning", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        UserAccount volAccnt = (UserAccount)nhwr.getReceiver();

        ViewVolunteerProfile viewVolunteerProfile = new ViewVolunteerProfile(userProcessContainer, volAccnt);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ViewVolunteerProfile", viewVolunteerProfile);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ViewVolunteerProfileBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LastName1;
    private javax.swing.JLabel LastName2;
    private javax.swing.JButton ViewVolunteerProfileBtn;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel firstName1;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField helpNameTxtField;
    private javax.swing.JTable helpRequestsJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JTextField serviceTypeTxtField;
    private javax.swing.JButton submitTestimnialBtn;
    private javax.swing.JTextArea testiTxtAreaField;
    private javax.swing.JLabel viewYourProfile;
    private javax.swing.JLabel viewYourProfile1;
    private javax.swing.JLayeredPane writeTestPanel;
    private javax.swing.JButton writeTestimonialBtn;
    // End of variables declaration//GEN-END:variables
}
